name: Provision t2.micro EC2
on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string
      destroy:
        description: Destroy Environment
        type: boolean
        required: false        
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - name: Destroy Environment
        if: inputs.destroy == true          
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
           terraform init
           terraform apply -destroy -auto-approve
           
      - name: Run Terraform
        if: inputs.destroy == false
        run: |
          terraform --version
          terraform init --upgrade
          terraform plan
      - name: Manual  Approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: tvinodh
          minimum-approvals: 1
          issue-title: "Approvals fron terraform"
          issue-body: "Please approve or deny the deployment" 
          
      - name: Terraform apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |          
            terraform apply 
            
