name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        run: |
          npm install -g snyk
          snyk auth
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
