name: Snyk Security Scan

on:
  pull_request:
    branches:
      - main  # Adjust to match your default branch

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: |
          curl -o snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk
          mv snyk /usr/local/bin/
          snyk test --all-projects

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
